#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



def fibonacci():
  a = 1
  b = 1
  sum = 0

  sum2 = 0

  while sum < 4000000:
    if sum % 2 == 0:
      sum2 += sum
    sum += b  
    b = a
    a = sum
    
  return sum2

suma = fibonacci()
    
print(suma)